### PR TITLE
Add date range selectors and file exporting

### PR DESCRIPTION
**Pull request by alexgleason**
screenshot-2018-6-18 wagtail - analytics

This lets you select a date range and then export it to a .ods file.

### CODE REVIEW

**Comment by alexgleason** [comment]
Before merging this I'm going to go back and see if I can improve some of the code, which is a little messy compared to the previous work done on it.

I'm wondering if @JamesRamm is still interested in this project at all. I modified your code to introduce date selectors instead of predefined buttons, but am afraid it's not as organized as yours. Would appreciate if you're willing to give it a look.

**Comment by JamesRamm** [comment]
If possible, I would separate the commits into 2 PR's - one for 'Add Date Range Selectors' and one for 'Exporting'.

**Comment by alexgleason** [comment]
I'm going to go ahead and merge it. It works in my browser on my machine, without any bugs.

I think we can just increment it a major version. @tomdyson would you be willing to deploy this? Or to add me to the package on PyPi (`alexgleason`).

**Comment by tomdyson** [comment]
Thanks @alexgleason! I've added you as a maintainer on PyPI: https://pypi.org/project/wagalytics/

**Pull request merged**
