### PR TITLE
Set Up Handling for Wagalytics Multisite

### PR DESCRIPTION
**Pull request by jake-kent**

### CODE REVIEW

**Comment by jake-kent** [comment]
@tomdyson I'd appreciate your feedback on this PR. Please let me know if there's another way you'd approach this or alternatively any blockers you see for merging this into the next release.

**Comment by KalobTaulien** [comment]
Hey @jake-kent 

Thanks for your contribution! 

I opened a new PR for some extended support for multiple GA instances, see #39 for my implementation. I found a lot of inspiration in your code so I've added you to the [Contributors list in the README file](https://github.com/tomdyson/wagalytics/pull/39/commits/30fa13bbaf98b122d69ea3dda8a4dfc6d8c5331a)

Once #39 is merged in I'll close this PR. Thanks again for the awesome work you did in here!

**Comment by jake-kent** [comment]
Hey @KalobTaulien 

Understood, thanks for pulling in some of my code to the new and adding me to the contributors list.

I'd be curious to hear why you chose to have the sites be declared manually in a settings file rather than be data-driven (set through the CMS). Is it for compatibility reasons?

Thanks for your work in getting this up and running nonetheless! I'm happy I could provide some inspiration.

**Comment by KalobTaulien** [comment]
That's a good question. Mainly just because it's currently less to maintain and for people who are reading their ga-key.json file if they are given an upload option they may not entirely have a secure setup and that could potentially expose their API information. Someone might also wonder about permissions and who should see/update/delete that data and who shouldn't, so there'd need to be a permission manager probably (open for discussion, of course).

Although in hindsight that's not really the responsibility of this package, is it (file security; also open for discussio). That'd be a good feature to have as well.

**Pull request closed without merging**
