### PR TITLE
Uses ChartJS for rendering and adds date selection

### PR DESCRIPTION
**Pull request by JamesRamm**
Hi @tomdyson 
Thanks for this great plugin. 
Apologies if this PR is not the direction you want to take wagalytics; it was just interesting & useful to my own project!

### Changes
Broadly, there are 3 changes in this PR:
- Use ChartJS for rendering the analytics data
- Switch from tables to bar charts for popular pages & referrers (this is subjective but I find a quick glance at a bar chart more informative than a quick glance at a table and also this was quicker to do!)
- Add ability to switch between last 7 and last 30 days for each charts' date range. 

### Points for discussion

- I have used ES6 syntax, so this means it is only compatible with modern-ish browsers (the last few versions of all major browsers support it, but older ones, for example any IE browser will not). If this is a problem, it would need extra work to compile the assets when publishing to pypi. 
- I just used random colours from Wagtails' colour palette. Let me know any preferences....
- I'd like to do some further changes - adding more views of data, control over max-results, but this might be best handled in a separate issue?

### CODE REVIEW

**Comment by tomdyson** [comment]
This is great, @JamesRamm - thanks a lot!

In response to your points:

> Use ChartJS for rendering the analytics data

I'm happy with this.

> Switch from tables to bar charts for popular pages & referrers (this is subjective but I find a quick glance at a bar chart more informative than a quick glance at a table and also this was quicker to do!)

This doesn't (currently) work well with long titles:

screenshot 2017-04-28 16 29 30

> Add ability to switch between last 7 and last 30 days for each charts' date range.

Great!

> I have used ES6 syntax, so this means it is only compatible with modern-ish browsers (the last few versions of all major browsers support it, but older ones, for example any IE browser will not). If this is a problem, it would need extra work to compile the assets when publishing to pypi.

I'd rather not rule out _all_ IE browsers. Can you document the compilation steps?

> I just used random colours from Wagtails' colour palette. Let me know any preferences....

These look fine to me.

> I'd like to do some further changes - adding more views of data, control over max-results, but this might be best handled in a separate issue?

Yes, a separate issue would be great.

**Comment by JamesRamm** [comment]
Hi
Long titles is an issue yes. It *should* be possible to format the labels (just cut them off basically, maybe with a '...', or cut them at the end of the host address) and keep the long version in the tool tip, which could be one solution. Its not clearly documented in ChartJS how to do this so might need a bit of wrangling. 

For compiling; to the end user there would be no difference. To the developer, they would need to have nodejs&npm installed and run a command (e.g. `npm run build`) each time they changed the JS.

I would need to add a webpack config file, a `package.json` file and a custom `Sdist` class or similar in `setup.py` so that the assets are built when running `setup.py`

**Comment by JamesRamm** [comment]
@tomdyson 
I have updated the PR to include compilation from ES6 to ES5 to support older browsers. 
To users, there is no difference in usage. To developers/git-cloners, they need to do the following steps:

- make sure nodejs & npm are installed
- cd to the repo
- `npm install` and `npm run build`
They will need to run `npm run build` anytime the javascript is changed. 
The JS source is moved to the `client` directory. The compiled JS is output in the `static` directory

**Comment by tomdyson** [comment]
Thanks @JamesRamm! Can you add your developer instructions to the README? I'd be happy to merge this with either 

- a fix for the long title problem, or
- a reversion of the table->bar chart change (which could go in a future PR)

**Comment by JamesRamm** [comment]
@tomdyson 
I have reverted back to tables for now since it turned out to be pretty tricky/hacky to make chartJS handle the labels nicely. Tables also allow showing more results neatly (with pagination), so I upped to max-results back to the original 25.

**Comment by JamesRamm** [comment]
README updated

**Comment by JamesRamm** [comment]
@tomdyson 
Hi; I think I have addressed your points for this now :)

**Comment by jayden2** [comment]
Curious to what has delayed this PR, or just forgotten?

**Pull request merged**
